### ISSUE TITLE
Question: How does this work?

### ISSUE THREAD

**Issue by IPWright83** [LinusBorg/vue-lib-monorepo-template#1]
Hey, hope you don't mind me dropping this in here as I've been testing this and it all seems to work really great... Namely that HMR just works in the monorepo setup. But I can't figure out how it works (as I want to get a similar result for a React project).

Your `lib` project specifies the entry point as ` "main": "dist/es5/lib.umd.js"` which I can see if I run a build. However when you launch the project Vite doesn't seem to use this built output, instead referencing the source directly. I can't see any configuration to tell it how to do this - do you know how it's working?

I've got a similar setup, where packages get built (currently using tsc not vite) into a `build` directory referenced in `package.json`. I'm using slightly different tech (pnpm) but the files are all linked through, rather than being considered part of `node_modules`.
```
    "main": "./build/index.js",
    "types": "./build/index.d.ts",
```

But I can't seem to get Vite using these files and trigger and HMR on change. The only way I can get it to work is to remap `main` to point at `src/index.ts` which I don't really want to do as that has a performance knock on for the other tools we're using.

So I'm wondering if you could shed some light on this? Or is this potentially a difference between Vue and React?

**Comment by LinusBorg** [comment]
I use an alias ointing directly to the src entry: 

https://github.com/LinusBorg/vue-lib-monorepo-template/blob/1bd83ec6251c5c6ee6d47970212c2b6a54879b6d/packages/playground/vite.config.ts#L10

**Comment by LinusBorg** [comment]
The linked file is the config for the playground app in which to demo your library.
The /lib folder itself has a separate vite config for bundling the library with vite.

**Comment by IPWright83** [comment]
How does bundling the `lib` folder itself help - if Vite is going to go straight to source? Or is this just to demo how you'd package up the library for other consumers?

**Comment by LinusBorg** [comment]
The latter. When playing around during dev, I include the source directly to get nice HMR, and then for publishing to npm I bundle it with vite.

**Comment by IPWright83** [comment]
Thanks for explaining @LinusBorg !
